### ISSUE TITLE
Return union types

### ISSUE THREAD

**Issue by Ehesp** [exaby73/luthor#18]
Hello!

One aspect of Zod which works well with TypeScript is the union types returned from parsing/validating a schema:

```js
const input = z.string().safeParse(123);

console.log(input.data) // type error!

if (!input.success) {
  console.log(input.message);
  return;
}

console.log(input.data) // ok!
```

Based on the readme, at the moment the result doesn't handle this scenario which makes things less type safe. Using freezed unions, you could internally return a `Validation` union, something like:

```dart
final result = l.string().validate('hello');

result.when(
  success: (String value) => print(value),
  error: (String message) => throw Exception(message),
)
```

**Comment by exaby73** [comment]
Thanks @Ehesp for the suggestion :)
