### ISSUE TITLE
Incorrect return types at StringValidator

### ISSUE THREAD

**Issue by kasefuchs** [exaby73/luthor#80]
The Email and DateTime validator returns a `Validator` instead of a `StringValidator`, which prevents the creation of validator chains in the context of using code generation. 

https://github.com/exaby73/luthor/blob/35dd2c9fae7b9742164393f69632920c0a19de57/packages/luthor/lib/src/validators/string_validator.dart#L21-L31

![image](https://github.com/exaby73/luthor/assets/64592097/2455a254-e51e-4309-b358-fe2a5372851d)

**Comment by exaby73** [comment]
Fixed in version 0.4.2+1 :)
