### ISSUE TITLE
Incorrect check for the existence of fromJson

### ISSUE THREAD

**Issue by kasefuchs** [exaby73/luthor#86]
https://github.com/exaby73/luthor/blob/cd5ef342599e1dd6ad595ecb53ff0fce0d873a90/packages/luthor_generator/lib/generators/luthor_generator.dart#L33-L41

There is no logical negation in `if (hasFromJsonCtor)`, which breaks code generation.

**Comment by exaby73** [comment]
Ahh sorry! Let me get a fix out

**Comment by exaby73** [comment]
Fixed in 0.4.4+2
